// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSfLd_jq1Lp45ADckJdxR6srGohBPiBzo',
    appId: '1:65392586596:web:dcd7e35bd0520099711471',
    messagingSenderId: '65392586596',
    projectId: 'fbtest-c2365',
    authDomain: 'fbtest-c2365.firebaseapp.com',
    storageBucket: 'fbtest-c2365.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABY30dFDcVMcYyKd2AynkbiXC-o5JTi-o',
    appId: '1:65392586596:android:ac08f17dbb12967d711471',
    messagingSenderId: '65392586596',
    projectId: 'fbtest-c2365',
    storageBucket: 'fbtest-c2365.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDddL0368FF7nlMgySO544EZRhDxNTUcWs',
    appId: '1:65392586596:ios:01c259ccca069cc5711471',
    messagingSenderId: '65392586596',
    projectId: 'fbtest-c2365',
    storageBucket: 'fbtest-c2365.firebasestorage.app',
    iosBundleId: 'com.example.fbtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDddL0368FF7nlMgySO544EZRhDxNTUcWs',
    appId: '1:65392586596:ios:01c259ccca069cc5711471',
    messagingSenderId: '65392586596',
    projectId: 'fbtest-c2365',
    storageBucket: 'fbtest-c2365.firebasestorage.app',
    iosBundleId: 'com.example.fbtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSfLd_jq1Lp45ADckJdxR6srGohBPiBzo',
    appId: '1:65392586596:web:f4ba17fc21d0da45711471',
    messagingSenderId: '65392586596',
    projectId: 'fbtest-c2365',
    authDomain: 'fbtest-c2365.firebaseapp.com',
    storageBucket: 'fbtest-c2365.firebasestorage.app',
  );

}